config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :tasks do
      put :toggle_check, on: :member
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, presence: true

  def percentage_done
    return 0 if tasks.count.zero?
    (tasks.completed.count.to_f / tasks.count.to_f) * 100
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :description, presence: true

  scope :completed, -> { where(task_check: true) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :lists, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  validates :name, presence: true
  validates :password, length: { minimum: 6 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def home
    render 'users/home'
  end

protected
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:account_update, keys: [:name])
   end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = current_user.lists.all.order("created_at DESC")
  end

  def show
    @tasks = @list.tasks.all
  end

  def new
    @list = current_user.lists.new

    respond_to do |format|
      format.js
    end
  end

  def create
    @list = current_user.lists.new(list_params)

    if @list.save
      respond_to do |format|
        format.html { redirect_to root_path }
      end
    else
      flash[:errors] = @list.errors.full_messages
      render :new
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @list.update(list_params)
      redirect_to root_path
    else
      flash[:errors] = @list.errors.full_messages
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

  def find_list
    @list = current_user.lists.find_by(id: params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_list
  before_action :find_task, only: [:update, :edit, :toggle_check, :destroy]

  def index
    @tasks = @lists.tasks
  end

  def new
    @task = @list.tasks.new

    respond_to do |format|
      format.js
    end
  end

  def create
    @list = current_user.lists.find_by(id: params[:list_id])
    @task = @list.tasks.new(task_params)

    if @task.save
      respond_to do |format|
        format.html { redirect_to list_path(@list) }
      end
    else
      flash[:errors] = @task.errors.full_messages
      render :new
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to list_path(@list) }
      end
    else
      flash[:errors] = @task.errors.full_messages
      render :edit
    end
  end

  def toggle_check
    @task.update(task_check: !@task.task_check) if @task
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@list) }
    end
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end

  def find_list
    @list = current_user.lists.find_by(id: params[:list_id])
  end

  def find_task
    @task = @list.tasks.find_by(id: params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <input name="authenticity_token" 
               type="hidden" 
               value="<%= form_authenticity_token %>"/>
    
    <% if user_signed_in? %>
      <nav class='navbar'>
      <ul>
        <li><h2 class='header'><%= link_to 'TODO', root_path, class: 'nav-links' %></h2></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-links navbar-brand' %></li>
      </ul>
      </nav>
    <% end %>

    <div class ="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<div class='modal-header'>
  <button type='button' class='close' data-dismiss='modal'>x</button>

  <div class='flash-errors'>
    <% if flash[:errors] %>
      <% flash[:errors].each do |alert| %>
        <p class='alert'><%= alert %></p>
      <% end %>
    <% end %>
  </div>

</div>

<div class='modal-body'>
  <%= simple_form_for @list, remote: true, class: 'list-form form-group' do |f| %>
    <%= f.input :title, label_html: { class: 'form-control-file' } %>
    
  <span class='modal-footer'><%= f.button :submit, class: 'btn create-list' %></span>
  <% end %>
</div>

app/views/lists/edit.js.erb
$('#modal-window').find(".modal-content").html("<%= j (render 'lists/form') %>")
$('#modal-window').modal();

$('.modal-header').append("<h3>Edit list</h3>")

app/views/lists/index.html.erb
  <h2><%= "Welcome #{current_user.name}" %></h2>
  <h3>Your lists</h3>
  
  <% if @lists.blank? %>
    <h5>You do not have any list</h5>
  <% else %>
    <table class='table table-striped'>
      <thead class='thead'>
          <th>List name</th>
          <th>Number of tasks</th>
          <th>% done</th>
          <th></th>
      </thead>
      <tbody>
      <% @lists.each do |list| %>
        <tr class="list-<%= list.id %>">
          <td><%= list.title %></td>
          <td><%= list.tasks.count %></td>
          <td><%= number_to_percentage(list.percentage_done, precision: 2) %></td>
          <td class='links'>
            <%= link_to "Show", list_path(list), class: "list-link" %> |
            <%= link_to "Edit", edit_list_path(list), { remote: true, 'data-toggle': "modal", 'data-target': "#modal-window", class: "list-link" } %> | 
            <%= link_to "Delete", list_path(list), method: :delete, class: "list-link" %> | 
            <%= link_to "Add task", "/lists/#{list.id}/tasks/new", { remote: true, 'data-toggle': "modal", 'data-target': "#task-modal-window", class: "list-link" } %>
            <div id='task-modal-window' class='modal hide fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
              <div class='modal-dialog' role='document'>
                <div class='modal-content'></div>
              </div>
            </div>
          </td>
          
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

<p><%= link_to "Add a list", new_list_path, { remote: true, 'data-toggle': "modal", 'data-target': "#modal-window", class: "btn btn-lg" } %></p>
<div id='modal-window' class='modal hide fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'></div>
  </div>
</div>

app/views/lists/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'lists/form') %>");
$("#modal-window").modal();

$('.modal-header').append("<h3>Add list</h3>")

app/views/lists/show.html.erb
<h3><%= @list.title %></h3>

  <div id='list_id' data-list-id= <%= @list.id %>>
  <% @tasks.each do |task| %>
      <p class='task-holder'>
        <span class='just-label'>
          <%= check_box_tag "task_id[#{task.id}]", 0, task.task_check, class: "task-check task-#{task.id}", data: { task_id: task.id } %>
          <%= label_tag "task_#{task.id}", "#{task.description}", class: 'task-description' %>
        </span>

          <span class='task-links'>
            <%= link_to "/lists/#{@list.id}/tasks/#{task.id}/edit", { remote: true, 'data-toggle': 'modal', 'data-target': '#task-modal-window', class: 'edit-icon' } do %>
              <i class='fa fa-pencil' aria-hidden='true'></i>
            <% end %>

            <%= link_to "/lists/#{@list.id}/tasks/#{task.id}", method: :delete, class: 'delete-icon' do %>
              <i class='fa fa-trash' aria-hidden='true'></i>
            <% end %>
          </span>
            <div id='task-modal-window' class='modal hide fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
              <div class='modal-dialog' role='document'>
                <div class='modal-content'></div>
              </div>
            </div>
      </p>
  <% end %>
  </div>

<%= link_to 'Add a task', "/lists/#{@list.id}/tasks/new", { remote: true, 'data-toggle': 'modal', 'data-target': '#task-modal-window', class: 'list-link btn btn-secondary' } %>
<div id='task-modal-window' class='modal hide fade' role='dialog' aria-labelledby='myModalLabel' aria-hidden='true'>
  <div class='modal-dialog' role='document'>
    <div class='modal-content'></div>
  </div>
</div>
<p><%= link_to 'Back to lists', root_path, class: 'back-to-lists' %></p>


app/views/tasks/_form.html.erb
<p class='notice'><%= notice %></p>

<div class='modal-header'>
  <button type='button' class='close' data-dismiss='modal'>x</button>
  
  <div class='flash-errors'>
    <% if flash[:errors] %>
      <% flash[:errors].each do |alert| %>
        <p class='alert'><%= alert %></p>
      <% end %>
    <% end %>
  </div>
</div>

<div class='modal-body'>
  <%= simple_form_for [@list, @task], remote: true, class: "form-group" do |f| %>
    <%= f.input :description, label_html: { class: "form-control-file" } %>

    <span class='modal-footer'><%= f.button :submit, class: "btn create-list" %></span>
  <% end %>
</div>

app/views/tasks/edit.js.erb
$('#task-modal-window').find('.modal-content').html("<%= j (render 'tasks/form') %>")
$('#task-modal-window').modal()

$('.modal-header').append("<h3>Edit task</h3>")

app/views/tasks/new.js.erb
$('#task-modal-window').find('.modal-content').html("<%= j (render "tasks/form") %>")
$('#task-modal-window').modal()

$('.modal-header').append("<h3>Add task</h3>")